# Generated by Django 4.2.2 on 2023-06-21 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_user_name_user_first_name_user_mail_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Cliente',
        ),
    ]
