# Generated by Django 4.2.2 on 2023-06-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_instrumento_precio_alter_instrumento_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='img',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
