# Generated by Django 4.2.2 on 2023-06-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_instrumento_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumento',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
