# Generated by Django 4.2.2 on 2023-06-23 20:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_alter_instrumento_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='instrumento',
        ),
        migrations.AddField(
            model_name='compra',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='compra',
            name='instrumentos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=200)),
                ('total', models.IntegerField(default=0)),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.instrumento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.cliente')),
            ],
        ),
    ]
