# Generated by Django 4.2.2 on 2023-06-23 20:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_remove_compra_desc_remove_compra_instrumento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='instrumento',
        ),
        migrations.AddField(
            model_name='carrito',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='carrito',
            name='instrumentos',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
