# Generated by Django 4.2.2 on 2023-06-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_remove_carrito_desc_remove_carrito_instrumento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='user',
        ),
        migrations.AddField(
            model_name='compra',
            name='cliente_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
