# Generated by Django 4.2.2 on 2023-06-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_remove_compra_user_compra_cliente_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='user',
        ),
        migrations.AddField(
            model_name='carrito',
            name='cliente_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
